### PR TITLE
Update .GitHub

### PR DESCRIPTION
**Pull request by TonybynMp4**
## Description
Yup

### CODE REVIEW

**Review by D4isDAVID — CHANGES_REQUESTED** [review]
We don't need the markdown (`.md`) issue templates because we already have issue forms (`.yml`).

**Comment by TonybynMp4** [comment]
> We don't need the markdown (`.md`) issue templates because we already have issue forms (`.yml`).

oh hmm this github thing is hard damn

**Review by D4isDAVID — APPROVED** [review]
Would be very nice if you could update `.github/contributing.md` as well.

**Review by D4isDAVID — APPROVED** [review]
Looks good.

**Pull request merged**
